# Generated by Django 3.2.23 on 2023-11-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_review_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/nike.jpg', null=True, upload_to=''),
        ),
    ]
