Products = [
    {
        '_id': '1',
        'name': 'Airpods',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality sound. It has active noise cancellation.',
        'brand':'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Nike',
        'image': '/images/nike.jpg',
        'description': 'Introducing the epitome of style and athletic prowess - Nike Jordans. Step up your sneaker game with these iconic kicks that seamlessly blend street fashion and high-performance design.',
        'brand':'Apple',
        'category': 'Electronics',
        'price': 0.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },
   {
        '_id': '3',
        'name': 'Nike',
        'image': '/images/nike2.jpg',
        'description': 'Introducing the epitome of style and athletic prowess - Nike Jordans. Step up your sneaker game with these iconic kicks that seamlessly blend street fashion and high-performance design.',
        'brand':'Apple',
        'category': 'Electronics',
        'price': 0.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Nike',
        'image': '/images/nike3.jpg',
        'description': 'Introducing the epitome of style and athletic prowess - Nike Jordans. Step up your sneaker game with these iconic kicks that seamlessly blend street fashion and high-performance design.',
        'brand':'Apple',
        'category': 'Electronics',
        'price': 0.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Airpods',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality sound. It has active noise cancellation.',
        'brand':'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 0,
        'rating': 2,
        'numReviews': 12,
    },
    {
        '_id': '6',
        'name': 'Airpods',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality sound. It has active noise cancellation.',
        'brand':'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 2.5,
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'Airpods',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality sound. It has active noise cancellation.',
        'brand':'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    }
]

